# Generated by Django 3.2.4 on 2021-06-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='idCelular',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Celular'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='idCompania',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Compañia'),
        ),
    ]
